test view k8s manifest

diff --git a/.github/workflows/deploy-db.yaml b/.github/workflows/deploy-db.yaml
--- a/.github/workflows/deploy-db.yaml
+++ b/.github/workflows/deploy-db.yaml
@@ -35,3 +35,43 @@ jobs:
           echo ${{ secrets.DOCKERHUB_TOKEN }} | helm registry login registry-1.docker.io -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin 
           helm push tta-v0.1.tgz oci://registry-1.docker.io/sarthaknazkani
         shell: bash
+
+
+      - name: Azure - Login
+        uses: azure/login@v1
+        with:
+          creds: ${{ secrets.AZURE_CREDENTIALS }}
+
+
+      - name: Log in AKS cluster
+          run: |
+            az aks get-credentials --resource-group baserg --name testakssarthak --admin
+          shell: bash
+
+      - name: Display k8s manifests via helm template
+        run: |
+          helm pull oci://registry-1.docker.io/sarthaknazkani/tta --version v0.1d ./charts --untar
+          helm template tta ./charts/threetierapp \
+          -f <(cat ./charts/threetierapp/values.yaml 2>/dev/null) \
+          -f ./charts/threetierapp/values-*.yaml \
+          -f <(echo "${{ inputs.values }}") \
+        shell: bash
+
+        # - name: Deploy via helm upgrade
+        #   run: |
+        #     helm rollback ${{ inputs.helm-chart-name }} $(helm history ${{ inputs.helm-chart-name }} -n ${{ inputs.namespace }} | grep deployed | cut -d$'\t' -f 1) -n ${{ inputs.namespace }} || true
+
+        #     helm upgrade ${{ inputs.helm-chart-name }} ./charts/${{ inputs.helm-chart-name }} \
+        #     --debug \
+        #     --install \
+        #     -n ${{ inputs.namespace }} \
+        #     -f <(cat ./charts/${{ inputs.helm-chart-name }}/values.yaml 2>/dev/null) \
+        #     -f ./charts/${{ inputs.helm-chart-name }}/values-${{ inputs.environment }}.yaml \
+        #     -f <(echo "${{ inputs.values }}") \
+        #     --atomic \
+        #     --cleanup-on-fail \
+        #     --wait \
+        #     --wait-for-jobs \
+        #     --timeout ${{ inputs.timeout }} \
+        #     --set namespace=${{ inputs.namespace }}
+        #   shell: bash
